---
name: Stale

on:
  schedule:
    - cron: '0 0 * * 0'

permissions:
  contents: read

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@3a9db7e6a41a89f618792c92c0e97cc736e1b13f # v10.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 60
          days-before-close: 30
          exempt-issue-labels: needs-triage
          exempt-pr-labels: needs-review
          remove-stale-when-updated: true
          delete-branch: false
          stale-issue-label: stale
          stale-issue-message: |
            I'm marking this issue as stale due to inactivity. This helps me
            focus on active discussions and issues.

            If there is no further activity on this issue, it will be
            automatically closed in 30 days.

            — [Ryan Johnson](https://github.com/tenthirtyam)
          stale-pr-label: stale
          stale-pr-message: |
            I'm marking this pull request as stale due to inactivity. This
            helps me focus on active pull requests.

            If there is no further activity on this pull request, it will
            be automatically closed in 30 days.

            — [Ryan Johnson](https://github.com/tenthirtyam)
